### PR TITLE
Footer changed

### PR DESCRIPTION
**Pull request by karthiknadar1204**
old Footer
Screenshot 2023-05-20 at 1 49 19 PM

Enhanced Footer
Screenshot 2023-05-21 at 11 16 11 AM

Have removed the package-lock json file as well,i think the updated version looks good now,have changed the social links from vertical to horizontal

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@Mansi168 @MonalikaPatnaik Have tried resolving the conflict on a separate branch,removed the json file before pushing the branch.

**Comment by karthiknadar1204** [comment]
I followed all the steps in the readme,previously the branch had conflicts because of the package lock-json so i ran an extra command to remove the package lock json file before pushing the changs to the staging area

**Comment by Mansi168** [comment]
hey @karthiknadar1204 please remove the social media column from the website and put icons in the bottom as it was earlier!

**Comment by karthiknadar1204** [comment]
Will do by evening @Mansi168 ,any other issues?

**Comment by karthiknadar1204** [comment]
@Mansi168 How do these changes look to you
Screenshot 2023-05-21 at 4 46 55 PM
Should i push these changes into the branch

**Comment by Mansi168** [comment]
yess, icons are looking perfect, but plz place that copyright back to centre :')

**Comment by karthiknadar1204** [comment]
ok will do right away and push the changes

**Comment by karthiknadar1204** [comment]
Screenshot 2023-05-21 at 4 57 48 PM
This should do i gues,is that right @Mansi168

**Comment by Mansi168** [comment]
yes...it is perfect now :)

**Comment by karthiknadar1204** [comment]
Pushed more changes to the branch,removed the package-lock json file as well,please intimidate me about any other conflict @Mansi168

**Comment by karthiknadar1204** [comment]
Should i delete the file package-lock-json in the files changed section here?

**Comment by Mansi168** [comment]
yes do not push package lock files......stage only those files in which you have made changes

**Comment by karthiknadar1204** [comment]
followed all the steps in the readme,previously the branch had conflicts because of the package lock-json so i ran an extra command to remove the package lock json file before pushing the changs to the staging area

are these steps correct @Mansi168 because these were the steps that i just followed.

Could you share the process to stage only those files in which i have made changes, like here i majorly dealt with only two files so how do i only add these 2 files.

Your help would be really appreciated as it would help me going forward into the program @Mansi168 @MonalikaPatnaik .

I thought of wrapping up this pr by day end today, another reason...

**Comment by karthiknadar1204** [comment]
@i-am-SnehaChauhan was there something wrong with my pr, it might be problematic going forward as i am still not aware about how to go about with it. I think i did a decent job, still need help with pushing the changes.
please guide me and suggest any improvements that i can make going forward

**Comment by karthiknadar1204** [comment]
@Mansi168 @MonalikaPatnaik

**Comment by Mansi168** [comment]
To stage specific file u need to run command 
git add fileName (for example git add app.js)
this will stage only required or changed files :)

**Comment by MonalikaPatnaik** [comment]
> @i-am-SnehaChauhan was there something wrong with my pr, it might be problematic going forward as i am still not aware about how to go about with it. I think i did a decent job, still need help with pushing the changes. please guide me and suggest any improvements that i can make going forward

Heyy..I think the pr was closed by confusion..don't worry..
will merge it..Thanks for the pr!
You did a good job!

**Comment by karthiknadar1204** [comment]
Will do it right away

**Comment by karthiknadar1204** [comment]
Not any issue but since i have already pushed the changes into the branch,it is showing this
Screenshot 2023-05-21 at 7 28 04 PM

How do i resolve this @Mansi168

**Comment by Mansi168** [comment]
Don't worry, we are looking into this!

**Comment by Google-Ka-Dinosaur** [comment]
Screenshot (189)

Hello! Kindly have a look at this footer design. I would like to implement something similar with a few changes to the colours to match the theme.

**Comment by Mansi168** [comment]
hey @karthiknadar1204 plz mention assigned issue for labelling :)

**Comment by karthiknadar1204** [comment]
Yes in a min

**Comment by karthiknadar1204** [comment]
#20 
@Mansi168

**Comment by Mansi168** [comment]
thanks :)

**Pull request merged**
