### PR TITLE
Add animation to cards in Our Services section

### LINKED ISSUE #83: Add animation to cards in Services section
I want to add an animation to the cards present in 'Our Services' section. It will be reflected on moving to this section.

I am GSSOC'23 contributor, kindly assign this issue to me.

### PR DESCRIPTION
**Pull request by khushigupta123**
## Fixes Issue
Closes #83 

## Changes proposed

- Added animation to Our Services section cards using Framer Motion library and install the dependency in project packages.

- Added CardAnimation.js file inside Services folder to avoid index.js file from getting bulky.

- Animation appears on entry whenever section comes in view.

https://github.com/MonalikaPatnaik/UMatter/assets/78090164/b6befedc-38d8-44c6-922a-6783b87445ca

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hey..thanks for the PR!
will merge it soon after resolving conflicts!

**Comment by khushigupta123** [comment]
> Hey..thanks for the PR! will merge it soon after resolving conflicts!

Thank you ma'am for letting me work on this issue, this was my first PR for GSSOC'23.
If there is anyway I can help in resolving conflicts, kindly guide me, I will do the needful.

**Comment by MonalikaPatnaik** [comment]
Heyy..your branch is giving conflicts because it is not in sync with the main..Could you sync it and add your code again?

**Comment by khushigupta123** [comment]
> Heyy..your branch is giving conflicts because it is not in sync with the main..Could you sync it and add your code again?

Sure ma'am

**Pull request closed without merging**
