### PR TITLE
Phone Country Selector Added

### PR DESCRIPTION
**Pull request by Nishitbaria**
Closes: #784

This pull request adds an international telephone input selector to the project. The selector allows users to choose their country, displaying the country flag and calling code. The telephone number format adjusts accordingly based on the selected country, ensuring correct formatting.

### Changes Made

1. Added the following code to `src\Components\Signup\index.js`:

```javascript
import PhoneInput, {
  formatPhoneNumberIntl,
  isPossiblePhoneNumber,
} from "react-phone-number-input";
```

2. Added the import statement for `"./PhoneInput.css"`.

3. Added the `handleOnChangePhoneNumber` function:

```javascript
const handleOnChangePhoneNumber = (inputValue) => {
  setValue(inputValue);
  const countrySelect = document.querySelector(".PhoneInputCountrySelect");
  const selectedCountryCode = countrySelect.value;
  setData({
    ...data,
    countryCode: selectedCountryCode,
    contactNumber: formatPhoneNumberIntl(inputValue),
  });
};
```

4. Updated the component from:

```jsx
<PhoneContainer>
  <FormInput
    onChange={(e) =>
      setData({ ...data, countryCode: e.target.value })
    }
    id="CountryCode"
    type="text"
    placeholder="+XXX"
  ></FormInput>
  <FormInput
    onChange={(e) =>
      setData({ ...data, contactNumber: e.target.value })
    }
    id="ContactNumber"
    type="text"
    placeholder="Phone Number"
    maxLength={10}
  ></FormInput>
</PhoneContainer>
```

to:

```jsx
<PhoneContainer>
  <PhoneInput
    international
    defaultCountry="IN"
    countryCallingCodeEditable={true}
    placeholder="Phone number"
    value={value}
    onChange={handleOnChangePhoneNumber}
  />
</PhoneContainer>
```

5. Updated the `validatecontactNumber` function for validation from:

```javascript
const validatecontactNumber = (contactNumber) => {
  // name should contain only alphabets
  const contactNumberRegex = /^\d{10}$/;
  return contactNumberRegex.test(contactNumber);
};
```

to:

```javascript
const validatecontactNumber = (contactNumber) => {
  // name should contain only alphabets
  return isPossiblePhoneNumber(contactNumber);
};
```

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

## Screen Shot

image

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hey @MonalikaPatnaik  Please Assign me to  issue

**Comment by Nishitbaria** [comment]
Hey @MonalikaPatnaik  Please Review my PR

**Comment by MonalikaPatnaik** [comment]
Hii, looks good to me..could you make the icons responsive for smaller screens...

**Comment by Nishitbaria** [comment]
@MonalikaPatnaik Thanks for Reviewing , but I have assigned issued already #1005

**Comment by Nishitbaria** [comment]
> @MonalikaPatnaik Thanks for Reviewing , but I have assigned issued already #1005
Please Update me regarding it

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik Thanks for Reviewing , but I have assigned issued already #1005

Okok my bad..didn't see that

**Pull request merged**
