### PR TITLE
Sign-in and Sign-up Page Design Improved

### LINKED ISSUE #773: Improvement in SignIn SignUp Pages
### Describe the feature

Hey, 
From the design point of view, There are some issues with the Sign in and Sign up pages in the current version. 
Issues: 

1. There are too many colours when you first open either page (grey, white, back, navy blue, green buttons, gradient box) and I feel they are not going too well somehow.
2. Continue button should look distinct with respect to the background (it is blending in).
3. Size of the continue button is not the same on both pages.
4. When you hover over the continue button, it changes to a muted orange colour (not in the colour palette or branding) and scales in size which is going out of the boundaries of the signup box.
5. Font size of the Headings "sign in to your account" and "create an account" are not uniform.
6. Size of sign-in/sign-up box changes when you switch between the two.
7. Input field of sign up menu is greater in height as compared to the fields of sign in menu
8. Overall look and feel is too bold.

image
image
image

### Add ScreenShots

Improvements - 

1. Simplifying the UI of the page as shown below
2. Uniforming the headings, box size, input field size, button size, font size
3. Overall More formal, designed look in accordance with the branding and color palette.

image
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by yogeyyy**
## Fixes Issue

Closes #773

Hey, 
I hope this message finds you well. I've been working on addressing some design issues in the Sign-in and Sign-up pages of the project. I have made the following changes:- 

## Changes proposed

1. Simplified UI: I've implemented a cleaner and more cohesive color scheme across the pages.
2. Enhanced "Continue" button: The "Continue" button(now "Sign In" / "Sign up") now has a distinct appearance that stands out from the background.
3. Uniform button sizes: I've ensured that the size of the "Continue" button is consistent between the Sign-in and Sign-up pages.
4. Refined hover effects: The hover effect on the "Continue" button now adheres to the branding and stays within the boundaries of the sign-up box. 
5. Consistent font sizes: The font sizes of the headings have been adjusted to provide a unified look.
6. Stable box size: The sign-in/sign-up box maintains a consistent size when transitioning between the two.
7. Harmonized input field height: I've made sure that the input field heights are consistent across both the sign-in and sign-up menus.
8. Overall visual improvements: The design has been refined to provide a more formal and polished appearance, aligned with the project's branding and color palette.

I believe these changes significantly enhance the user experience and bring a more cohesive and visually appealing design to the Sign-in and Sign-up pages.

I kindly request you to review my changes and consider merging the PR into the main repository. I'm open to any feedback or further adjustments you may suggest. Thank you for your time and consideration.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
LGTM! You can add images irrespective of the text in dark green part! something like this maybe--( not exactly this image but something that looks good) and also make the white part of form a bit wide..
image

**Comment by yogeyyy** [comment]
> LGTM! You can add images irrespective of the text in dark green part! something like this maybe--( not exactly this image but something that looks good) and also make the white part of form a bit wide.. image

Sure, I'll push the changes soon. :)

**Comment by yogeyyy** [comment]
Hey @MonalikaPatnaik , 
I have made the desired changes, based on your latest feedback. I kindly request you review my changes and consider merging the PR into the main repository.
Thanks.

**Comment by MonalikaPatnaik** [comment]
Thankyou so much...looking good to me!

**Pull request merged**
