### PR TITLE
minor css changes in navbar

### PR DESCRIPTION
**Pull request by mahekkg**

### CODE REVIEW

**Comment by mahekkg** [comment]
Please Review

**Comment by i-am-SnehaChauhan** [comment]
Hii, @mahekkg Can u please share an image like what u have done?

**Comment by mahekkg** [comment]
> Hii, @mahekkg Can u please share an image like what u have done?

Screenshot (365)
Screenshot (362)
Screenshot (363)
Screenshot (364)


Have tried to fix basic alignment of navbar and changed the style of sign in button which works well with corresponding navbar design.
Thank you

**Comment by MonalikaPatnaik** [comment]
Hey..I see your branch is not in sync with the main branch..I recommend to first sync it(git pull origin main) then submit a PR

**Comment by MonalikaPatnaik** [comment]
Hey..I am unassigning you this..since it's long and already.. there are lot of navbar related issues!

**Pull request closed without merging**
