### PR TITLE
resolved pswrd position button

### PR DESCRIPTION
**Pull request by rohanmittal1163**
##description
Hey @MonalikaPatnaik 
I have created The PR.
I have changed the position of password toggle button and set to it center
pls review it

#Proposal
hey @MonalikaPatnaik I have created an issue where i mention about the changin the design of blog section and make it more cleaner
I want to add this
image
the middle is on hover animation

if you are okay with it I will be happy to contribute to it

## Fixes Issue
closes - #458 

## Changes proposed

image

[ ] - Not correct; marked as **not** done-->

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

Thank you for assigning

### CODE REVIEW

**Comment by rohanmittal1163** [comment]
Hey @MonalikaPatnaik
Can i create this blog section you jave assigned me if this design is ok then i can create this?

**Comment by MonalikaPatnaik** [comment]
> Hey @MonalikaPatnaik Can i create this blog section you jave assigned me if this design is ok then i can create this?
What's the issue number?

**Comment by rohanmittal1163** [comment]
Its

#457

**Comment by MonalikaPatnaik** [comment]
Actually a related PR is merged, let me review that & get back to u!

**Comment by rohanmittal1163** [comment]
Ok sure

**Pull request merged**
