### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shivam-sharma7**

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @MonalikaPatnaik

**Comment by Mansi168** [comment]
hey @shivam-sharma7 The correct way to keep your cloned repository synchronized with the upstream main repository is to pull from the upstream repository and merge any changes into your local branch not push as you mentioned!

**Comment by shivam-sharma7** [comment]
That will create an extra merge commit! @Mansi168 This way you can pull in your main and push as well without creating an extra merge commit

**Comment by Mansi168** [comment]
@shivam-sharma7 thanks for contributing :)

**Pull request merged**
