### PR TITLE
Fixed bug and added animation to testimonial section

### LINKED ISSUE #763: BUG: Fixing Testimonial Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey, @MonalikaPatnaik The heading and buttons of the testimonials section are not visible in light mode. Please assign me this issue. Thank you!

### Add ScreenShots

- Dark Mode:-

image

- Light Mode:-

image

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sumitkr2000**
## Fixes Issue

Closes #763 

## Changes proposed

Hey @MonalikaPatnaik I have fixed the bug in the testimonial section. Earlier heading and buttons were not visible in light mode. Now it is completely visible. I have also added Swiper js which is a famous library for adding slier to websites.

- Screenshot:-

Before:-
image

After:-
testimonial

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hey the testimonial section is not visible to me..pls check once!

**Comment by sumitkr2000** [comment]
> Hey the testimonial section is not visible to me..pls check once!

Hey @MonalikaPatnaik is the backed server also deployed online?

**Comment by sumitkr2000** [comment]
Because I have used backend data to render. There were also some data in the testimonial file. Which one do I have to render?? CAN YOU CLARIFY IT ONCE?

**Comment by MonalikaPatnaik** [comment]
> Because I have used backend data to render. There were also some data in the testimonial file. Which one do I have to render?? CAN YOU CLARIFY IT ONCE?

Hii, the backend of the project is not deployed yet..you could use dummy data for testimonials as of now..also you could raise a new issue regarding deployment of backend...then we can update the testimonials section maybe!

**Comment by sumitkr2000** [comment]
Hey @MonalikaPatnaik I am opening a new pull request because I cannot resolve the conflict in the .db file. I am closing this one.

**Pull request closed without merging**
