### PR TITLE
user authentication using jwt

### PR DESCRIPTION
**Pull request by souravbhunia07**
Users can now log in and signup.

### CODE REVIEW

**Comment by Mansi168** [comment]
Hey @souravbhunia07 after making account after entering all the details in signup......signin is not working with all these details
here is the ss of the error i m getting...!
image

**Comment by souravbhunia07** [comment]
Actually, I provide the APIs only for authentication and it needs to be integrated to the frontend. you can check it in Postman.
In Postman it runs fine.

like this:-
Register
image

login
image

logout
image

**Comment by Mansi168** [comment]
ohkkayyyy!

**Comment by MonalikaPatnaik** [comment]
Hey @souravbhunia07 I think backend is already been added but the thing is we cannot sign-up and login..I think the token is not generating or matching maybe...Could you pls look into that and update your PR by syncing your branch!
Thank you so much for your patience!

**Comment by TechSpiritSS** [comment]
merge conflicts since 3 weeks so I am closing this.

**Pull request closed without merging**
