### PR TITLE
#899 page designed

### LINKED ISSUE #899: Feat: i can design a page for all things that are yet to be developed
### Describe the feature

i can design a under construction page for our site and link all the footer things that are yet to be developed.

https://[smilebirddental.com/in/aboutus](https://smilebirddental.com/in/aboutus)
link for reference

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by k-deepak04**
## Changes proposed

image

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by k-deepak04** [comment]
@MonalikaPatnaik please review this one

**Comment by MonalikaPatnaik** [comment]
LGTM !
However, you could align the text and image to center of the page and place the paragraph `This page is currently under development. Please check back later` above the image and below the heading Umatter development.
Also, you could redirect this page to Careers, Investors and Terms of Services in footer section.

**Comment by k-deepak04** [comment]
Okay will do the needful

**Comment by k-deepak04** [comment]
@MonalikaPatnaik now check
done everything you said

also i can design the careers and other pages for your project
you can give me some reference website and i will do the needful
Do let me know :)

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik now check done everything you said
> 
> also i can design the careers and other pages for your project you can give me some reference website and i will do the needful Do let me know :)

Yes sure..if u could find something good, you could raise a new issue and share the link/ss/video of the same..If we find it good, will assign it to you!

**Pull request merged**
