### PR TITLE
Added the Consult with doctor webpage

### PR DESCRIPTION
**Pull request by Prajwal0225**
## Fixes Issue
#865 

## Changes proposed

https://github.com/MonalikaPatnaik/UMatter/assets/103810119/d809ee1c-1221-433f-95c6-4e9969b864ec

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Prajwal0225** [comment]
Heey @MonalikaPatnaik can you please check my Pr #863 
You forgot to label it 😅.

Can you please add the appropriate Labels to it so that my pr gets counted in my gssoc'23 contribution...

**Comment by MonalikaPatnaik** [comment]
Hii, some spare area is showing below the footer..also, could you make the form for " Make an appointment" a bit attractive?
image

**Comment by MonalikaPatnaik** [comment]
> Heey @MonalikaPatnaik can you please check my Pr #863 You forgot to label it 😅.
> 
> Can you please add the appropriate Labels to it so that my pr gets counted in my gssoc'23 contribution...

Hii, level labels are only added to the merged prs not on the closed ones.

**Comment by Prajwal0225** [comment]
> Hii, some spare area is showing below the footer..also, could you make the form for " Make an appointment" a bit attractive? image


Ok, I will make the changes.

**Comment by Prajwal0225** [comment]
@MonalikaPatnaik please check the new form ⤵️ 
I do some improvements to make it more attractive my following the website color theme.

https://github.com/MonalikaPatnaik/UMatter/assets/103810119/eaa5c8a6-51be-43f9-97a6-9b666f800e2a

And no space is showing after the footer on my end 😅 

no space

**Pull request merged**
