### PR TITLE
Added Animations and Fixed Button cursor

### PR DESCRIPTION
**Pull request by AmanSinghBhogal**
Hey @MonalikaPatnaik ,
I am an GSSoC'23 Contributor, So in this PR I have added Animation to the Project using framer-motion library, which is an popular react library for animations. Along with this I noticed that the buttons were having a typo in the cursor spelling due to which cursor was not being pointer on buttons. I have attached a demonstration video for this:

https://github.com/MonalikaPatnaik/UMatter/assets/45331015/e8fe6202-6ab6-4350-9211-e1225375424e

Please let me know if any changes needed from my side

### CODE REVIEW

**Comment by Mansi168** [comment]
hey @AmanSinghBhogal well done!
Thanks for contributing!

**Comment by AmanSinghBhogal** [comment]
Will my PR be merged?😅

**Comment by Mansi168** [comment]
yess i have merged...i was dealing with merge conflicts :')

**Comment by Mansi168** [comment]
hey @AmanSinghBhogal plz mention assigned issue!

**Pull request merged**
