### PR TITLE
Darkmode added in mobile dimensions

### LINKED ISSUE #451: No dark mode for mobile dimensions
**Describe the bug**

There is no dark mode for mobile dimensions.I  can add  dark mode in the Navbar in the mobile dimensions. Can you assign this task to me?GSSOC23
**Screenshort**
WhatsApp Image 2023-05-27 at 19 28 52

### PR DESCRIPTION
**Pull request by Shreyans2004**
## Fixes Issue
Closes #451

## Changes proposed
The darkmode is added in mobile dimensions also.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Heyy could u change it like this! Currently visibility of dark/light mode is not that much in mobile menu..
image
image

**Comment by Shreyans2004** [comment]
Yes .SURE!!

**Comment by Shreyans2004** [comment]
Done . Now it is looking like the second screenshot .

**Comment by MonalikaPatnaik** [comment]
Heyy..don't change the alignment of the current button! I told you to improve the visibility of the button as it is in website view
image
See it's not that visible!

**Comment by Shreyans2004** [comment]
Now the button is aligned back to its position and it's visibility is improved in the dark mode.

**Comment by Shreyans2004** [comment]
Can you please attach labels to this PR?

**Comment by MonalikaPatnaik** [comment]
> Can you please attach labels to this PR?

Hey level labels are added to issues not PRs!

**Comment by Shreyans2004** [comment]
Oh .Thanks for the information.

**Pull request merged**
