### PR TITLE
Fixed the footer

### PR DESCRIPTION
**Pull request by karthiknadar1204**
The old footer
Screenshot 2023-05-20 at 1 49 19 PM

The Enhanced footer
Screenshot 2023-05-20 at 5 23 25 PM

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@Mansi168 What is the conflict with package.json,i dont get it

**Comment by Mansi168** [comment]
only push changed files except package.json and package-lock.json

**Comment by MonalikaPatnaik** [comment]
Social media icons in vertical column is not looking good to me..Could you revert this?

**Comment by KashiwalHarsh** [comment]
Hii I can fix this issue by upgrading the visited and underlining in the org name with horizontal icons with working links 
Under GSSOC can you please assign this issue to me

**Comment by karthiknadar1204** [comment]
@Mansi168 Will do the changes and submit pr again

**Comment by karthiknadar1204** [comment]
Should i make the social media icons horizontal on the same lines or do you have something else on mind

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik @Mansi168 could you guide me on how to add specific files to the pr,like is it just adding the package.json file to gitignore or is there some other steps to be followed

**Comment by Mansi168** [comment]
@karthiknadar1204 stage necessary changed files only !

**Comment by karthiknadar1204** [comment]
please check #143 branch,made a different pr on a separate branch

**Pull request merged**
