### PR TITLE
add: submit button for contact page

### PR DESCRIPTION
**Pull request by shivam-sharma7**
add placeholder for contact page

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Button is not looking nice to me!Change it to like the button there in sign in page
image

**Comment by shivam-sharma7** [comment]
> Button is not looking nice to me!Change it to like the button there in sign in page  

okay

**Comment by MonalikaPatnaik** [comment]
Heyy @shivam-sharma7..also don't tell the contributors to close their issues..we will reach out to them if any further improvemnts are needed or will close their issues by our own!

**Comment by shivam-sharma7** [comment]
hey @MonalikaPatnaik I was doing that because so many folks creating same issue. But now I will not do that

**Pull request merged**
