### PR TITLE
Added the blog about how meditation help the developer by Parmesh Bhatt

### PR DESCRIPTION
**Pull request by Parmesh119**
Closes issue #817 

## Changes proposed
I have added the article related to how meditation helps the developer because meditation is very important for the developer to think logically. 
Please review it and If it is fine then please merge it to the main branch.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
hey pls resolve the conflicts in your branch!

**Comment by Parmesh119** [comment]
I have resolved the conflict.

**Comment by MonalikaPatnaik** [comment]
Resolve this error--
image

**Comment by MonalikaPatnaik** [comment]
You can add a new image for new blog 🙂

**Pull request closed without merging**
