### PR TITLE
add theme-switch button

### PR DESCRIPTION
**Pull request by An525ish**

### CODE REVIEW

**Comment by i-am-SnehaChauhan** [comment]
Hii, @An525ish can u share a picture or video like how is it visible now?

**Comment by An525ish** [comment]
> Hii, @An525ish can u share a picture or video like how is it visible now?

Sure mam........this is how it gonna look like....
localhost_3000_UMatter (1)
localhost_3000_UMatter

**Comment by Mansi168** [comment]
okay this is perfect :)
thanks for contributing!

**Comment by Mansi168** [comment]
but hey @An525ish remove package-lock.json file from commited files and again make a pr after staging only changed files

**Comment by Mansi168** [comment]
Also sync your fork before pushing :')

**Comment by Mansi168** [comment]
hey @An525ish plz mention assigned issue for labelling !

**Comment by An525ish** [comment]
> hey @An525ish plz mention assigned issue for labelling !

it's done....

**Pull request merged**
