### PR TITLE
#495 work done

### LINKED ISSUE #495: on clicking forgot passward does not show otp to recorrect it.. in signup section
**Describe the bug**

**Screenshort**

### LINKED ISSUE #897: BUG: opt section retry issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

on clicking resend otp we should get a pop-up otp resend sucessfully but it's taking us out at home page, i can use react-toastify to achieve this functionality and also debug to correct the redirect issue.

### Add ScreenShots

https://github.com/MonalikaPatnaik/UMatter/assets/96341431/b9ea1bf6-1208-4360-aa09-6b5c44ac5e3d

### What browser are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by k-deepak04**
used good coding practice making all the things in function for future scalability and checked eveything is working good using react functionality like toastify and useEffect,useState for timer

## Changes proposed
sucessful
image

retry 
image

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by k-deepak04** [comment]
Bug of redirecting home page done + i have added other things also :)

**Comment by k-deepak04** [comment]
@MonalikaPatnaik please review this

**Comment by k-deepak04** [comment]
also i have few changes suggestions

current contact page
image

proposed idea
image
image

**Comment by k-deepak04** [comment]
we can add FAQ section also as it's present on all major websites for customer satisfaction

proposed desgin

image
image

**Comment by k-deepak04** [comment]
and i thought of adding one section like why choose us
image

**Comment by k-deepak04** [comment]
@MonalikaPatnaik do let me know if anything aligns with your idea 
i will create one separate issue and you can tell me the changes there

**Comment by MonalikaPatnaik** [comment]
Hiii, Thank you so much..you can create separate issues for faq page and why choose us part..
The faq part should be added after testimonial section and you can add it to the navbar.
Why choose us section, you can add it anywhere where you find it good!

**Comment by k-deepak04** [comment]
@MonalikaPatnaik please merge this PR so i can create another one :)

**Comment by k-deepak04** [comment]
🤧
Okay will do

**Pull request closed without merging**
