### PR TITLE
Updated UI for navbar

### PR DESCRIPTION
**Pull request by Anupreet1213**
Updated UI for navbar.

Previous: 

image

Newer: 

https://github.com/MonalikaPatnaik/UMatter/assets/93524594/2992d8bf-954c-40b8-a51b-0cd895c34b19

----------------------------------------

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Heyy Anupreet.. I liked your navbar design..Could you please make a separate branch sync it with main, incorporate your changes and submit a Pr again..will merge it..

**Comment by Anupreet1213** [comment]
@MonalikaPatnaik Ok I will do it. But what exactly you want me to do? Do you want me to create a new branch with my code and updated code (of main branch)? 
To do so, I have to remove the current navbar. So please clarify things.

And thanks for approaching :)

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik Ok I will do it. But what exactly you want me to do? Do you want me to create a new branch with my code and updated code (of main branch)? To do so, I have to remove the current navbar. So please clarify things.
> 
> And thanks for approaching :)

Hey..I saw your updated_navbar branch is 154 commits behind the main branch...So, I mean to say that sync your branch and incorporate your code then..

**Comment by Anupreet1213** [comment]
@MonalikaPatnaik I have updated the code and now it's not behind main branch.

**Comment by MonalikaPatnaik** [comment]
Hey..just add the sign-up button in the navbar!
thankyouu!

**Comment by Anupreet1213** [comment]
@MonalikaPatnaik You want two buttons(Sign in and Sign Up) on navbar?
If that is case I will add it but it's not gonna look great there. It will make it cluttered.

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik You want two buttons(Sign in and Sign Up) on navbar? If that is the case I will add it but it's not gonna look great there. It will make it cluttered.

Yes ik @Anupreet1213 ..The sign up page is already made..so for now just add it to the navbar..further we will remove it and add a button like "Don;t have a account--Sign up here" or something like that in the Signin/Login Page, which will redirect to the sign up page...

**Comment by Anupreet1213** [comment]
@MonalikaPatnaik It's done from my side, you can check it.

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik It's done from my side, you can check it.

Heyy..LGTM!
Thanks for Contributing!

**Pull request merged**
