### PR TITLE
habit Tracker included #689

### PR DESCRIPTION
**Pull request by Piyusharora2003**
## Fixes Issue
#689 

## Changes proposed
- added the habit tracker
- It takes up the local data
- Page added and styled accordingly.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

## Screenshots

umat

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hii. since it is of level 3, I expect you could make it responsive and for the done status you could add a add a checkbox rather than this edit icon..Also pls add some css to the table and add dark theme to this <3

**Comment by MonalikaPatnaik** [comment]
> No issues with the other changes, but the dark mode is a whole new issue for this.

Okay then do commit the other changes

**Comment by Piyusharora2003** [comment]
Here are the changes -
Laptop view-
image

Tablet View-
image

Mobile View -
image


Mobile view ( Iphone SE )-
image


Now the table is more responsive the edit icon is now removed and replace with the notifying icon 

I would like to work on implimenting the dark mode soon , but for that i need to know how to get the state of current theme as there is no state in the app.js, please tell me about how to get the state data then i would implement it

**Comment by Piyusharora2003** [comment]
@MonalikaPatnaik do review the changes

**Pull request merged**
