### PR TITLE
add PascalCase(#383)

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hey..I don't think it is required...the website is working fine without this!

**Comment by shivam-sharma7** [comment]
> Hey..I don't think it is required...the website is working fine without this!

Locally website not working due to

image

**Comment by shivam-sharma7** [comment]
the error has resolved

**Comment by MonalikaPatnaik** [comment]
> > Hey..I don't think it is required...the website is working fine without this!
> 
> But for a project we need to manage everything right and you can see contributors not chose right name for components there are lot of issue in project files as well. So the goal is to doing this to get best file/folder structure as well.

Hey..I see u have just converted the case of forgot password which is not required..also the mentioned issue has not been assigned to you..
Make contributions that can enhance the frontend of UMatter!

**Pull request closed without merging**
