### PR TITLE
Button and Mode Changing Button Color Pallet

### PR DESCRIPTION
**Pull request by ojasaklechayt**
1. Improved Buttons Color Pallet.
2. Added borders to buttons and mode changing button.

## Changes proposed

**Describe the solution you'd like**

1. Button Color Pallet

Before:
image

After: 
image

2. Mode Changing Button

Before:
image

After:
image

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@MonalikaPatnaik can you please check once?

**Comment by MonalikaPatnaik** [comment]
Heyy @ojasaklechayt you can't make PR to a issue until it is assigned! It's against the rules, we cann't merge it! 
As you have made a PR, I want to say the green color of button was looking fine..no need to change that...What you can do is-- you can improve the UI of the buttons in the website and can add a good hover effect!
Would you like to work on this?

**Comment by ojasaklechayt** [comment]
> Heyy @ojasaklechayt you can't make PR to a issue until it is assigned! It's against the rules, we cann't merge it! As you have made a PR, I want to say the green color of button was looking fine..no need to change that...What you can do is-- you can improve the UI of the buttons in the website and can add a good hover effect! Would you like to work on this?

Yeah Sure!! I will work on this

**Comment by MonalikaPatnaik** [comment]
> > Heyy @ojasaklechayt you can't make PR to a issue until it is assigned! It's against the rules, we cann't merge it! As you have made a PR, I want to say the green color of button was looking fine..no need to change that...What you can do is-- you can improve the UI of the buttons in the website and can add a good hover effect! Would you like to work on this?
> 
> Yeah Sure!! I will work on this

Okay, then I am changing the title of your current issue and assigning it to you..you can work on improving the UI of buttons..will merge your PR!
Right now I am closing this pR

**Pull request closed without merging**
