### PR TITLE
nabvar popup added issue #32

### PR DESCRIPTION
**Pull request by shuddhi-jain**
fixing the popover of the navbar #32 
Screenshot (45)

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hey the issue has not been assigned to you!

**Comment by shuddhi-jain** [comment]
Yeah the issue is not been assigned to me but, when you gave labels to my issue, I started working on it, and then you didn’t assign me, even I finished the work.  Sent from Mail for Windows From: Monalika PatnaikSent: 27 May 2023 09:49To: MonalikaPatnaik/UMatterCc: shuddhi-jain; AuthorSubject: Re: [MonalikaPatnaik/UMatter] nabvar popup added issue #32 (PR #300) Hey the issue has not been assigned to you!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by MonalikaPatnaik** [comment]
Okay @shuddhi-jain ..coming back to your PR, sync your branch and make a separate PR where you can add toggle button in the mobile pop up menu..the mobile pop up is added..what u can do is aligning sign-up sign-in buttons properly and adding toggle button..submit your PR soon!
Thanks for the patience...so as of now I am closing this PR and renaming the issue and assigning it to u..okay?

**Comment by shuddhi-jain** [comment]
okay thankyou @MonalikaPatnaik

**Pull request closed without merging**
