### PR TITLE
Fixed issue #719

### PR DESCRIPTION
**Pull request by ePSA-eJya**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

https://github.com/MonalikaPatnaik/UMatter/assets/120899038/1e93ccb2-8616-45b4-bf0c-4e7dd956f18c

please merge the pr @MonalikaPatnaik

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
The rapid hover effects are not looking good to me..you could add some delay in transition maybe..also in dark mode the text is not visible before the hover..

**Comment by ePSA-eJya** [comment]
> The rapid hover effects are not looking good to me..you could add some delay in transition maybe..also in dark mode the text is not visible before the hover..

ok would fix them

**Comment by ePSA-eJya** [comment]
@MonalikaPatnaik i am creating a new pr.

**Comment by ePSA-eJya** [comment]
review pr #872

**Pull request closed without merging**
