### PR TITLE
Supertopic is Updated

### PR DESCRIPTION
**Pull request by shubham-shinde-442**
Now it is Fixed.

Screenshot (691)

### CODE REVIEW

**Comment by shubham-shinde-442** [comment]
Can You Merge this pr ?

**Comment by shubham-shinde-442** [comment]
Issue #19

**Comment by MonalikaPatnaik** [comment]
Hey..actually the footer has changed a bit..could you make the topics bold in the latest footer..

**Comment by shubham-shinde-442** [comment]
Sure

**Comment by MonalikaPatnaik** [comment]
If you are facing conflicts on this branch, you can make a new branch and push you changes there..

**Pull request closed without merging**
