### PR TITLE
Fixed Navbar - made it responsive

### PR DESCRIPTION
**Pull request by 007aneesh**
Close this issue https://github.com/MonalikaPatnaik/UMatter/issues/2#issue-1717679183

Made a responsive navbar added tailwind CSS, and added the function to scroll to a particular element if you want to add more links to the navbar, iteration in the navbar is now very much easy. 

#2 solved ✅

### CODE REVIEW

**Comment by 007aneesh** [comment]
Check it thoroughly! Waiting for the reply!!!

**Comment by 007aneesh** [comment]
@MonalikaPatnaik have a look into this pr

**Comment by 007aneesh** [comment]
@MonalikaPatnaik  @i-am-SnehaChauhan @Mansi168  have a look at this pr

**Comment by Mansi168** [comment]
hey @007aneesh many people hv made pr for navbar...there are many conflicts....we have to look into this issue....will review your pr shortly :')

**Comment by 007aneesh** [comment]
Hey, @Mansi168 As I was assigned to this Navbar issue in #2 which was literally the first issue of the Navbar how can others work on that? This should be considered by collaborators!!

**Comment by MonalikaPatnaik** [comment]
Heyy...looks good to me..could you attach a ss for reference?

**Comment by MonalikaPatnaik** [comment]
> Hey, @Mansi168 As I was assigned to this Navbar issue in #2 which was literally the first issue of the Navbar how can others work on that? This should be considered by collaborators!!

heyy @007aneesh, as per your issue: #2 I think you have to make the navbar operational in mobile view..not to change the navbar as a whole..Could you just make the hamburger menu functional (that too in accordance with dark theme)?
Also, you can make a separate branch as this is having conflicts..will merge it..
Thanks for contributing! :-)

**Comment by 007aneesh** [comment]
Hi, @MonalikaPatnaik previous navbar is having some issues because that code was not written well it can lead to some issues related to navigation so that's why I changed it and my code is totally reusable and if you want to add new tabs to it then it is very easy and you will not face any issues related to navigation in the future. And I will add the dark theme feature today with the different branch. Is there any naming convention for a new branch?

Thanks

**Comment by 007aneesh** [comment]
@MonalikaPatnaik  If you are satisfied with why I have changed the navbar or want to just go with the hamburger functional then just reply to it. Thanks

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik If you are satisfied with why I have changed the navbar or want to just go with the hamburger functional then just reply to it. Thanks

Heyy @007aneesh..Thnkx for asking..I want you to just make the hamburger functional as the navbar as in whole is being handled by issue: #7
For that, you can make a separate branch and sync your repo with the main branch before making a PR( git pull origin main)..Also, I am not merging any navbar related PRs as of now bcoz it'll create conflicts..will merge yours first when u are done..So, I'm expecting your updated Pr soon!
Do let me ask for any issues!

**Comment by 007aneesh** [comment]
Thanks, @MonalikaPatnaik working on it.

**Pull request closed without merging**
