### PR TITLE
Redesigned Contact us Page

### LINKED ISSUE #536: Redesign Contact Us Page
**Feature idea.**
Our site's current contact us page doesn't look good. I'll redesign it beautifully. I am a GSSOC Contributor. Kindly assign this issue to me.

### PR DESCRIPTION
**Pull request by prjailani**
## Fixes Issue

Closes #536

## Changes proposed

Redesigned Contact us page

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Mansi168** [comment]
image
this is how ur changes are looking!
make them correct first!

**Comment by prjailani** [comment]
> image
> this is how ur changes are looking!
> make them correct first!

Isn't it good

**Comment by MonalikaPatnaik** [comment]
hii, could you change your contact page a bit like this..don't make the contact container too wide!
Thanks for ur patience!
image

**Comment by prjailani** [comment]
> hii, could you change your contact page a bit like this..don't make the contact container too wide! Thanks for ur patience! image

Sure. Please give me some time I will update and let you know.

**Comment by TechSpiritSS** [comment]
merge conflicts

**Comment by MonalikaPatnaik** [comment]
Hey @prjailani is it done? Any update?

**Comment by prjailani** [comment]
Hi, I'll give a commit within tomorrow. I had some homeworks previously.

**Pull request closed without merging**
