### PR TITLE
added feedback section in navbar

### LINKED ISSUE #341: Adding website's icon to the navbar and a feedback section for users to share their growth .
1. For styling the website, add the icons of Umatter to the navbar along the name "Umatter".
2. Adding another section in navbar ass feedback, for users to connect more and share their growth in the process of quitting bad habits.

Please assign this issue to me under GSSoC'23 label :)

### PR DESCRIPTION
**Pull request by Akanksha-202**
## Fixes Issue
Fixed issue no. #341 
Closes #341 

## Changes proposed

-- Added feedback and testimonials section in navbar
--Added feedback column in database SQL table
-- Under feedback section, user can input their username and feedback.
-- If already existing user fills the input, the feedback gets updated, else if new user is filling in the data, new item gets created with user_id, username and feedback only.
--Under testimonials section, latest 3 feedbacks are retrieved on the homepage.
--Added proxy to package.json file of client side in order to connect with backend express and sql.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

##Video 

Here is the video preview of working of the new sections:
https://www.loom.com/share/32525258bb54484aa202cd71fac84baa

##Screenshots
image
image
image

### CODE REVIEW

**Comment by i-am-SnehaChauhan** [comment]
Hey... @Akanksha-202 instead of these carts in testimonial change it with carousel coz it is not looking good right now.

**Comment by Mansi168** [comment]
hey @Akanksha-202 testimonials have been assigned to other person.....I m merging ur feedback so do not make any further changes :)

**Comment by Akanksha-202** [comment]
@Mansi168 The testimonials which I made are dynamic, the feedback of users is displayed as the testimonials and I made the feedback session, so I made all the connections and structure of code in that way!

**Comment by Mansi168** [comment]
did your pr require any changes?

**Comment by Akanksha-202** [comment]
No, its all ready, justv that one of the collaborator, sneha asked to do some styling, else everything is done and working

**Pull request merged**
