### PR TITLE
UI of search bar improved in blogs Page

### PR DESCRIPTION
**Pull request by Geeta259**
#900

## Changes proposed

Improved Search bar section by added some CSS properties on it to look it good.
Add search icon embedded on search bar
Improved Clear button UI.

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- Screenshot (466)]

@MonalikaPatnaik Please review it issue#900 resolved.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
It is not responsive for smaller screens

**Comment by Geeta259** [comment]
> It is not responsive for smaller screens

Ok I do!

**Comment by Geeta259** [comment]
> It is not responsive for smaller screens

@MonalikaPatnaik  Now check this Pr#925 hope it's work!!

**Comment by MonalikaPatnaik** [comment]
LGTM...Can you add outline color to green or some similar color in the input type?

**Comment by MonalikaPatnaik** [comment]
Add Outline color to green in the input type i.e when the input is active, it is hovered to green, don't add border to it..lmk if u face any issues :)

**Pull request merged**
