### PR TITLE
About and services section Revamp

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Fixes Issue
#519 

## Changes proposed
Have added containers for the about us and the services section making it look more engaging and made it perfectly responsive.

Screenshot 2023-06-16 at 9 27 06 PM

Screenshot 2023-06-16 at 9 27 16 PM

Screenshot 2023-06-16 at 9 28 11 PM

Some issues faced were that I was unable to dynamically change the colour of the containers, couldn't figure out the reason for the same, probably issues with my browser, have kept a neutral yellow color for the containers.
The containers are perfectly responsive .

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Services section
Screenshot 2023-06-16 at 9 35 14 PM

**Comment by Mansi168** [comment]
hey @karthiknadar1204 yellow color is too bright, cards in services section must not have yellow color, website is not responsive after your changes, your changes are not visible in dark mode!!

If you could solve all these issues in your pr, then only i will merge your pr, otherwise i have to close it!!!

**Comment by karthiknadar1204** [comment]
Hii @Mansi168 ,As for the color, i'll fix it, as for the colour changes in light-dark mode, There are issues in my browser, I have tried making it change dynamically but it is constantly showing error in my console.
As for the responsiveness, please check it again, I have made the component fully responsive after being told to do that by @MonalikaPatnaik .

For the light dark mode issue, please refer the chats in issue #519 , I have shared the details of the issue faced along he with appropriate images.

Do you have any other color in mind that should be added, I'll add it accordingly.

This is my second pr , in the first pr, I forgot about the responsiveness and dynamic colour change of the container .
In this pr I tried resolving it, I changed the colour, if this colour doesn't work out, I'll modify it further, check the chats in issue #519 , I spoke to @MonalikaPatnaik Before submitting a pr as probably issues in my system , I am unable to render the dynamic color change of the container in light and dark mode, Someone else could take up the issue for dynamic colour change, as for me, I'll make the components containerized along with responsiveness.

For responsiveness, please check again , if not working, I'll fix it, in the screenshot I shared, it was perfectly responsive.

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Should I resolve the branch conflicts and push the changes again with a new colour other than yellow?
Also please update me about the issue with responsiveness. I still don't get it.

**Comment by karthiknadar1204** [comment]
> @MonalikaPatnaik Should I resolve the branch conflicts and push the changes again with a new colour other than yellow? Also please update me about the issue with responsiveness. I still don't get it.

@Mansi168 @MonalikaPatnaik Let us wrap up this issue quickly, please share your opinion on my previous changes, and what is the responsiveness issue so that we can sort it out all at once, on my side, have already stated the dynamic colour change issue, someone else can work it out once we have sorted out the basic issues of responsiveness and colour of the container.

**Comment by MonalikaPatnaik** [comment]
Hey..looking at your PR! pls be patient..

**Comment by karthiknadar1204** [comment]
So sorry for the haste, the previous review was pretty vague so did not know how to proceed further.

**Comment by MonalikaPatnaik** [comment]
for the responsiveness, the horizontal bar is showing up if u notice(attached ss below)..for the color..change it to bit dark yellow (#f7b801) in the services section..for the cards..don't change the color inside the card..let it be white..you could checkout  codein community "meet the core team" section for reference..and try again to change color in dark mode as well🙂
image

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Will try to push these changes again, thank you for your patience, will also attempt dynamic colour changes

**Comment by karthiknadar1204** [comment]
Have started working on this issue again, will wrap up by weekend, Thank you for your patience guys

**Comment by MonalikaPatnaik** [comment]
If u are facing issues in this, don't waste much of your time😊there are lot of lot of issues in which u can work on❤️

**Comment by karthiknadar1204** [comment]
Sure, but think can get it right, will try my best, Thank you

**Pull request closed without merging**
