### PR TITLE
Update SignupElements.js box of passward and re-enter passward are pr…

### PR DESCRIPTION
**Pull request by 2020B1531074**
…operly arranged

#565

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by 2020B1531074** [comment]
#565 i have changed and arranged the passward and re-enter passward in a proper way.now,all box are of equal.

**Comment by Mansi168** [comment]
hey ur pr is giving me issues :(
plzz sync ur repo before making pr

**Comment by 2020B1531074** [comment]
On Sun, Jun 4, 2023, 10:25 PM Mansi ***@***.***> wrote:

> hey ur pr is giving me issues :(
> plzz sync ur repo before making pr
>
Mam, I have synced and in the screenshot you can see it the error is
resolved . Please merged it if it is not have please help me what I do

**Comment by 2020B1531074** [comment]
Thnku mam☺️

**Comment by 2020B1531074** [comment]
Mam please add the level of gssoc in my pr

**Pull request merged**
