### PR TITLE
About and services section revamp

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Fixes Issue
#519 

## Changes proposed
Have added containers for the about us and the services section making it look more engaging.

Screenshot 2023-06-11 at 1 28 54 PM

Screenshot 2023-06-11 at 1 29 03 PM

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik @Mansi168

**Comment by MonalikaPatnaik** [comment]
Hey..could you change the color theme...gray is not looking good to me..also the containers are nit changing according to the modes

**Comment by karthiknadar1204** [comment]
Will push the changes by day end @MonalikaPatnaik 
Thank you

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik ah so sorry for not abidong with the dark and light mode, do you have any other color scheme in your mind, I'll implement it accordingly

For the light mode, you can change it to yellow and for dark mode, maybe dark blue/violet something that looks good with black. make the containers responsive too!

**Comment by karthiknadar1204** [comment]
ohk, i think that works, have added the color changes, will make it responsive and push the changes again tomorrow @MonalikaPatnaik , hope that's fine.

**Comment by MonalikaPatnaik** [comment]
> ohk, i think that works, have added the color changes, will make it responsive and push the changes again tomorrow @MonalikaPatnaik , hope that's fine.

Absolutely!

**Comment by karthiknadar1204** [comment]
Screenshot 2023-06-14 at 8 58 07 PM

@MonalikaPatnaik   Have fixed the colors to be rendered on varying the light and dark mode but when I tried rendering the About component in index.js in DarkMode.js, it is showing this error and a blank screen, how do I proceed.

The color yellow goes well in both light as well a the dark mode for now,please refer the following attachments
Screenshot 2023-06-14 at 9 01 10 PM
Screenshot 2023-06-14 at 9 01 22 PM

If it works then will make it responsive and push the changes because have been trying to align the contents dynamically in DarkMode.js for the past 2 hrs with no concrete results.The console window shows the same error message.

**Comment by karthiknadar1204** [comment]
> 

Will try again

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Tried setting up the project again and implemented the same changes but still facing the same error message. Checked for any other application running on the same port but couldn't find any, cleared the cache as well before setting it up again.

Have made it perfectly responsive, and have commented the colour needed for the light and dark and light modes.
Have made it responsive as well.

On dynamic rendering the screen turns white and the console shows the following error:
react-refresh-runtime.development.js:315 Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at initializer.js:71:1
    at Array.map (<anonymous>)
    at n.load (initializer.js:80:1)
    at new t (typed.js:13:1)
    at index.js:91:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik your opinion, should i push these changes?

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik your opinion, should i push these changes?

Yes push it..

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Please refer pr #783 
Have added all the screenshots as well

**Pull request closed without merging**
