### PR TITLE
Blog page update

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Changes proposed

adding an animation effect to the blogs like only the heading of a particular blog will be visible, but when the user hovers over the blog, we could make the rest of the blog content visible to the user.

https://github.com/MonalikaPatnaik/UMatter/assets/95973644/eb316893-180a-4ec8-a410-ea169d8e9d9a

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
I pulled the main and added the files that were changed, cant figure out reason for conflict here

**Comment by karthiknadar1204** [comment]
Screenshot 2023-05-27 at 11 44 23 AM

**Comment by MonalikaPatnaik** [comment]
Hey..don't worry..will solve the conflicts & merge it soon!

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Any update ?
Was hoping to wrap it up by day end.

**Comment by MonalikaPatnaik** [comment]
heyy..i think the conflicts are of because you havn't sync your branch with main...it's hard to merge!
could you sync your branch & retry?

**Comment by karthiknadar1204** [comment]
Will try now

**Comment by shivam-sharma7** [comment]
> Will try now

you can solve this or you can open another PR but before making any contribution you need to first sync your local branch with upstream.

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Opening a new pr, done with implementing changes again

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Check pr #459 
Worked out a completely new pr, pulled the changes again and added the same features

**Pull request closed without merging**
