### PR TITLE
solved the sign up issue

### PR DESCRIPTION
**Pull request by Prashant-2505**
add google authentication by using firebase

add some other functionality like when user logged in there it will show profile instead of sign in

adding sign out functionality

when your signed in then it will redirect user to home page

when your signed out then it will redirect user to home page

i hope you will like the work and other extra functionality that i add

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Okay..will review it..
Thanks for the pr!

**Comment by Mansi168** [comment]
image
hey these are some files need to correct to avoid conflicts......plzz look into this

**Comment by Mansi168** [comment]
also first sync the repo, then make a pr!

**Comment by shivam-sharma7** [comment]
resolve merge conflicts

**Comment by MonalikaPatnaik** [comment]
Hii @Prashant-2505 I loved your work but unable to merge your branch since it's giving conflicts..Could you pls sync your branch and update or open a new PR?
Thankyou so much for your patience!

**Pull request closed without merging**
