### PR TITLE
Update Contact.js

### PR DESCRIPTION
**Pull request by 2020B1531074**
Add a placeholder in contactus section

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by i-am-SnehaChauhan** [comment]
Hey... You have to mention issue no in your PR
Firat tell your issue no.

**Comment by 2020B1531074** [comment]
#465

**Comment by i-am-SnehaChauhan** [comment]
@2020B1531074 you cann't make PR until the issue is assigned to you!
We cann't merge it... Wait for assigning then make your PR.
Thanks:)

**Comment by 2020B1531074** [comment]
Please assigned to me this

**Pull request closed without merging**
