### PR TITLE
Branch2:Fixed issue #719

### PR DESCRIPTION
**Pull request by ePSA-eJya**
## Fixes Issue
 #719 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

https://github.com/MonalikaPatnaik/UMatter/assets/120899038/c097155e-0844-4a67-925d-58257ccd2b50

improved transition timing....

https://github.com/MonalikaPatnaik/UMatter/assets/120899038/19d7e7b7-1f2a-4ced-85cb-6804102bf9d6

dark mode enabled
 
please merge the pr @MonalikaPatnaik @TechSpiritSS 
also please add a level label

### CODE REVIEW

**Comment by ePSA-eJya** [comment]
please merge the pr @MonalikaPatnaik @TechSpiritSS

**Comment by ePSA-eJya** [comment]
please merge the pr @MonalikaPatnaik @TechSpiritSS

**Comment by ePSA-eJya** [comment]
please merge the pr @MonalikaPatnaik @TechSpiritSS

**Comment by MonalikaPatnaik** [comment]
Hey yur branch is giving some error in deployment..also, as discussed with my fellow maintainers, the hover effect is not looking good...just add the green background to the card when it is hovered
image

**Comment by ePSA-eJya** [comment]
ok will fix that

**Comment by ePSA-eJya** [comment]
@MonalikaPatnaik i have created a new pr #951

**Comment by ePSA-eJya** [comment]
please merge the pr @MonalikaPatnaik @TechSpiritSS

**Pull request closed without merging**
