### PR TITLE
backend added

### LINKED ISSUE #907: Proper cleaning of backend code adding validators and Deployment
### Describe the feature

Here there is need of properly managing the backend code its not clean so cleaning of code is needed and need to add some JOI validates to solve the issue of getting broken data in Database and than deploy it on Vercel.

### No proper folder structure
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ja3mamtora**
## Fixes Issue

#Closes #907

## Changes proposed

- added proper folder structure for backend.
- added user schema
- added signin signup routes
- added yup validators

## Check List (Check all the applicable boxes) 

- [x] - Correct;  My code follows the code style of this project.
- [x] - Correct; My change requires changes to the documentation.
- [x] - Correct;  I have updated the documentation accordingly.
- [x] - Correct;  All new and existing tests passed.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hii, LGTM... @TechSpiritSS could you pls check it once?

**Comment by TechSpiritSS** [comment]
- Current PR contains generic backend code and it is missing many routes which were present in previous backend.
- The routes implemented are different from the initial ones eg. signin instead of login.
- The generated token is not being used or sent back in the response.
- Generic error messages

**Comment by Ja3mamtora** [comment]
okkay i will make the changes

**Comment by MonalikaPatnaik** [comment]
any update on this @Ja3mamtora ?

**Comment by Ja3mamtora** [comment]
Working on it would complete it by this weekend

**Pull request closed without merging**
