### PR TITLE
relevant change on the homepage

### PR DESCRIPTION
**Pull request by tanya172**
This is my first contribution to your project.
I have edited a single sentence on the page kindly allow the request as I did it to check the feasibility of my system and I am ready to make all the required improvements in the project.
Best Regards,
Tanya172

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
fixes #568

**Comment by tanya172** [comment]
I didn't get u..
What shouldn't be changed?

**Comment by MonalikaPatnaik** [comment]
Don't change " Make your life more blissful "

**Comment by tanya172** [comment]
I understand the fact but I asked you earlier I am here to increase the seo
of the website and enhance the content of it. So you assigned me with that
issue.
So please tell me am I allowed to change the content written in the website
in order to make it look more professional and valuable?

**Comment by tanya172** [comment]
Please reply

**Pull request merged**
