### PR TITLE
Added github badges to readme and updated readme

### PR DESCRIPTION
**Pull request by singh-anushka**
## Changes proposed

Updated the README file

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by singh-anushka** [comment]
Please merge this pr with gssoc23 and level 2 label to it.

**Comment by MonalikaPatnaik** [comment]
Thanks for the PR!
Will soon be adding level labels to it...don't worry!
Thanks!

**Comment by singh-anushka** [comment]
@MonalikaPatnaik kindly add gssoc23 label to it with level 2.

**Comment by singh-anushka** [comment]
@MonalikaPatnaik kindly add GSSoC23 and level 1 label to it.

**Pull request merged**
