### PR TITLE
Update UI design of Blog page as per Issue #340

### PR DESCRIPTION
**Pull request by SaiyamTuteja**
Description:
This commit implements a new UI design for the Blog page, addressing the requirements specified in Issue #340.

The changes made to the code include:

Redesigned layout: The layout of the Blog page has been revamped to enhance its visual appeal and usability. The new design aims to provide a more engaging and user-friendly experience for visitors.

Updated styling: The styling of various elements, such as the search container, blog cards, titles, content, and buttons, has been modified to align with the new UI design. The changes encompass color schemes, typography, spacing, and overall aesthetics, ensuring a cohesive and modern appearance.

Improved user interactions: The "Read More" button has been enhanced to provide a more intuitive and responsive user interaction. Clicking on the button now triggers a specific action, such as expanding the blog content or navigating to a separate page for detailed reading.

Responsiveness and adaptability: The new UI design takes into account different screen sizes and devices. The page layout and components have been optimized for responsiveness, allowing users to access and interact with the Blog page seamlessly across various devices, including desktops, tablets, and mobile devices.

These changes bring a fresh and visually appealing look to the Blog page, aligning with the objectives outlined in Issue #340. The updated UI design enhances the overall user experience, making it more engaging, intuitive, and accessible.

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hey your branch is giving me conflicts...it's hard to merge..so first sync your branch( git pull origin main) and then make a PR!

**Comment by SaiyamTuteja** [comment]
Screenshot (64)
Screenshot (65)
Screenshot (66)
these issues are faced by me

**Comment by MonalikaPatnaik** [comment]
Hey have u tried running ' git pull origin main'

**Comment by MonalikaPatnaik** [comment]
hey don't push your changes via codespaces..it gives u error...try visual studio

**Comment by SaiyamTuteja** [comment]
its already up to date
Screenshot (67)

**Comment by MonalikaPatnaik** [comment]
No,it's behind 23 commits...have u added the upstream link to the main branch...see contributing.md step 3 
Screenshot_2023-06-01-23-22-22-50_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by SaiyamTuteja** [comment]
now check and then merge it i have resolved the conflicts

**Comment by MonalikaPatnaik** [comment]
Hey..the blog page is looking like this--if u re facing difficulty in this..it's okay..you can do it later and can work on improving the search bar in blogs page! 
image

**Comment by SaiyamTuteja** [comment]
Sorry for this but don't know how it's happening I am working on the search button on blog page

**Comment by MonalikaPatnaik** [comment]
> Sorry for this but don't know how it's happening I am working on the search button on blog page

It's just okay...don't worry..u are doing good! Closing this PR, you can work on your assigned issue reg blogs cards later on and then submit a PR!

**Pull request closed without merging**
