### PR TITLE
Update index.js

### LINKED ISSUE #561: Read more hyperlink
**Describe the bug**

There are no attached hyperlinks to readmore section. To have original blogs that can actually help people with depression and anxiety would help them. 

**Screenshort**
image
 
Therefore I'd like to add real hyperlinks to the blog section for people to read. @MonalikaPatnaik

### PR DESCRIPTION
**Pull request by guha-rahul**
Closes  #561 
Added hyperlinks to all the blogs

### CODE REVIEW

**Comment by guha-rahul** [comment]
Hey i am struggling to understand why the workflows are failing

**Comment by Mansi168** [comment]
hey @guha-rahul please dont add hyper link on 2nd blog "what smoking does to your body" bcz currently all the pages are linked to same page , so u can link all other pages except 2nd page :)

**Comment by guha-rahul** [comment]
hey @Mansi168 thats why i changed the  `<Link to="">`  tag to `<a href = {blog.hyperlink} `, so that they can all have their individual hyperlinks instead of routing to "/abc"

**Comment by MonalikaPatnaik** [comment]
> hey @Mansi168 thats why i changed the `<Link to="">` tag to `<a href = {blog.hyperlink} `, so that they can all have their individual hyperlinks instead of routing to "/abc"

Hii @guha-rahul, what we are trying to say is that don't add a hyperlink to the 2nd blog, let it redirect to the /abc page..because this page is added by some contributor, we don't want to remove their changes that'why.. also you can add target="blank" to open the links in new tab!

**Comment by MonalikaPatnaik** [comment]
Hii @guha-rahul, any update on this?

**Comment by guha-rahul** [comment]
hey @MonalikaPatnaik sorry for the delay i was actually out of town . I have made the necessary code changes and will be submitting the new pr with the recommended changes asap!.

**Comment by MonalikaPatnaik** [comment]
Could you add links to the last two blogs as well.. will merge your PR!

**Comment by guha-rahul** [comment]
Sure!

**Pull request merged**
